[2025-02-01T00:53:14.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T00:53:15.065+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-01T00:53:09.533134+00:00 [queued]>
[2025-02-01T00:53:15.102+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-01T00:53:09.533134+00:00 [queued]>
[2025-02-01T00:53:15.104+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T00:53:15.168+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-02-01 00:53:09.533134+00:00
[2025-02-01T00:53:15.189+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T00:53:15.199+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-02-01T00:53:15.198+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'manual__2025-02-01T00:53:09.533134+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpjcswko09']
[2025-02-01T00:53:15.204+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask etl_ex_bbva
[2025-02-01T00:53:15.408+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-01T00:53:09.533134+00:00 [running]> on host 56024cb05cfe
[2025-02-01T00:53:15.714+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:53:09.533134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T00:53:09.533134+00:00'
[2025-02-01T00:53:15.717+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T00:53:15.838+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-01T00:53:15.840+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-02-01T00:53:15.905+0000] {subprocess.py:99} INFO - Output:
[2025-02-01T00:53:23.948+0000] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-01T00:53:23.949+0000] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-01T00:53:23.950+0000] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-01T00:53:23.952+0000] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-01T00:53:23.953+0000] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-01T00:53:24.013+0000] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-01T00:53:24.015+0000] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-01T00:53:24.016+0000] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-01T00:53:24.017+0000] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-01T00:53:24.019+0000] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-01T00:53:24.309+0000] {subprocess.py:106} INFO - 2025-02-01 00:53:24,308 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-02-01T00:53:24.316+0000] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-01T00:53:24.317+0000] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 2, 1)
[2025-02-01T00:53:24.324+0000] {subprocess.py:106} INFO - ic| query: '
[2025-02-01T00:53:24.325+0000] {subprocess.py:106} INFO -             SELECT * FROM calidad_etl.sm_cerrado
[2025-02-01T00:53:24.326+0000] {subprocess.py:106} INFO -                 WHERE "INSERTAR_DT" >= %s;
[2025-02-01T00:53:24.327+0000] {subprocess.py:106} INFO -             '
[2025-02-01T00:53:26.762+0000] {subprocess.py:106} INFO - 2025-02-01 00:53:26,762 - assets - INFO - SQL query succesfully executed
[2025-02-01T00:53:26.764+0000] {subprocess.py:106} INFO - 2025-02-01 00:53:26,764 - etl_ex_bbva - INFO - Start ETL Exito Tuya BBVA
[2025-02-01T00:56:07.415+0000] {subprocess.py:106} INFO - 2025-02-01 00:56:07,414 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-02-01T00:56:12.766+0000] {subprocess.py:106} INFO - 2025-02-01 00:56:12,765 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-02-01T00:56:12.768+0000] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-02-01T00:56:13.178+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-01T00:56:13.224+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T00:56:13.226+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=manual__2025-02-01T00:53:09.533134+00:00, execution_date=20250201T005309, start_date=20250201T005315, end_date=20250201T005613
[2025-02-01T00:56:13.290+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T00:56:13.326+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-01T00:56:13.330+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
