[2025-01-31T05:47:21.749+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T05:47:21.810+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-01-31T05:47:18.487555+00:00 [queued]>
[2025-01-31T05:47:21.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-01-31T05:47:18.487555+00:00 [queued]>
[2025-01-31T05:47:21.840+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T05:47:21.930+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-01-31 05:47:18.487555+00:00
[2025-01-31T05:47:21.965+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T05:47:21.984+0000] {standard_task_runner.py:72} INFO - Started process 3264 to run task
[2025-01-31T05:47:21.983+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'manual__2025-01-31T05:47:18.487555+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpb21i__ux']
[2025-01-31T05:47:21.999+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask etl_ex_bbva
[2025-01-31T05:47:22.305+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-01-31T05:47:18.487555+00:00 [running]> on host 09b63ee6c6d0
[2025-01-31T05:47:22.659+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T05:47:18.487555+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T05:47:18.487555+00:00'
[2025-01-31T05:47:22.662+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T05:47:22.753+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-31T05:47:22.758+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-01-31T05:47:22.794+0000] {subprocess.py:99} INFO - Output:
[2025-01-31T05:47:29.623+0000] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-01-31T05:47:29.625+0000] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-01-31T05:47:29.627+0000] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-01-31T05:47:29.628+0000] {subprocess.py:106} INFO -              'port': '3306',
[2025-01-31T05:47:29.630+0000] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-01-31T05:47:29.819+0000] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-01-31T05:47:29.821+0000] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-01-31T05:47:29.824+0000] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-01-31T05:47:29.825+0000] {subprocess.py:106} INFO -              'port': '3306',
[2025-01-31T05:47:29.827+0000] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-01-31T05:47:30.258+0000] {subprocess.py:106} INFO - 2025-01-31 05:47:30,258 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-01-31T05:47:30.270+0000] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 1, 1)
[2025-01-31T05:47:30.274+0000] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 1, 31)
[2025-01-31T05:47:30.282+0000] {subprocess.py:106} INFO - ic| query: '
[2025-01-31T05:47:30.285+0000] {subprocess.py:106} INFO -             SELECT * FROM calidad_etl.sm_cerrado
[2025-01-31T05:47:30.287+0000] {subprocess.py:106} INFO -                 WHERE "INSERTAR_DT" >= %s;
[2025-01-31T05:47:30.289+0000] {subprocess.py:106} INFO -             '
[2025-01-31T05:47:31.538+0000] {subprocess.py:106} INFO - 2025-01-31 05:47:31,537 - assets - INFO - SQL query succesfully executed
[2025-01-31T05:47:31.542+0000] {subprocess.py:106} INFO - 2025-01-31 05:47:31,541 - etl_ex_bbva - INFO - Start ETL Exito Tuya BBVA
[2025-01-31T05:51:14.407+0000] {subprocess.py:106} INFO - 2025-01-31 05:51:14,407 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-01-31T05:51:14.648+0000] {subprocess.py:106} INFO - ic| columnas_no_coincidentes: 'Columnas Iguales'
[2025-01-31T05:51:14.649+0000] {subprocess.py:106} INFO - 2025-01-31 05:51:14,648 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-01-31T05:51:14.670+0000] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-01-31T05:51:15.109+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-31T05:51:15.170+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T05:51:15.172+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=manual__2025-01-31T05:47:18.487555+00:00, execution_date=20250131T054718, start_date=20250131T054721, end_date=20250131T055115
[2025-01-31T05:51:15.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T05:51:15.253+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T05:51:15.326+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
