[2025-02-13T18:25:50.498-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T18:25:50.518-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-13T23:24:05.217618+00:00 [queued]>
[2025-02-13T18:25:50.530-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-13T23:24:05.217618+00:00 [queued]>
[2025-02-13T18:25:50.532-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-13T18:25:50.550-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): etl_ex_bbva> on 2025-02-13 23:24:05.217618+00:00
[2025-02-13T18:25:50.558-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=52259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T18:25:50.561-0500] {standard_task_runner.py:72} INFO - Started process 52261 to run task
[2025-02-13T18:25:50.561-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'etl_ex_bbva', 'manual__2025-02-13T23:24:05.217618+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpiw68047v']
[2025-02-13T18:25:50.562-0500] {standard_task_runner.py:105} INFO - Job 117: Subtask etl_ex_bbva
[2025-02-13T18:25:50.614-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.etl_ex_bbva manual__2025-02-13T23:24:05.217618+00:00 [running]> on host 21f1c1b48730
[2025-02-13T18:25:50.718-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='etl_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T23:24:05.217618+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T23:24:05.217618+00:00'
[2025-02-13T18:25:50.719-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-13T18:25:50.739-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-13T18:25:50.740-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/etl_ex_bbva.py']
[2025-02-13T18:25:50.752-0500] {subprocess.py:99} INFO - Output:
[2025-02-13T18:25:53.293-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-13T18:25:53.294-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-13T18:25:53.295-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-13T18:25:53.296-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-13T18:25:53.296-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-13T18:25:53.326-0500] {subprocess.py:106} INFO - ic| params: {'database': 'calidad_etl',
[2025-02-13T18:25:53.326-0500] {subprocess.py:106} INFO -              'host': '172.29.33.204',
[2025-02-13T18:25:53.327-0500] {subprocess.py:106} INFO -              'password': 'calidad2021*',
[2025-02-13T18:25:53.327-0500] {subprocess.py:106} INFO -              'port': '3306',
[2025-02-13T18:25:53.328-0500] {subprocess.py:106} INFO -              'user': 'calidad_etl'}
[2025-02-13T18:25:54.076-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:54,075 - assets - INFO - Engine para base de datos: calidad_etl creado exitosamente
[2025-02-13T18:25:54.080-0500] {subprocess.py:106} INFO - ic| hoy: datetime.date(2025, 2, 13)
[2025-02-13T18:25:54.081-0500] {subprocess.py:106} INFO -     fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-13T18:25:54.084-0500] {subprocess.py:106} INFO - ic| fecha_inicio: datetime.date(2025, 2, 1)
[2025-02-13T18:25:54.085-0500] {subprocess.py:106} INFO -     fecha_fin: datetime.date(2025, 2, 13)
[2025-02-13T18:25:54.089-0500] {subprocess.py:106} INFO - ic| query: '
[2025-02-13T18:25:54.089-0500] {subprocess.py:106} INFO -             SELECT * FROM calidad_etl.sm_cerrado
[2025-02-13T18:25:54.090-0500] {subprocess.py:106} INFO -                 WHERE "INSERTAR_DT" >= %s;
[2025-02-13T18:25:54.090-0500] {subprocess.py:106} INFO -             '
[2025-02-13T18:25:54.437-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:54,437 - assets - INFO - SQL query succesfully executed
[2025-02-13T18:25:54.438-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:54,437 - etl_ex_bbva - INFO - Start ETL Exito Tuya BBVA
[2025-02-13T18:25:58.994-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:58,994 - etl_ex_bbva - INFO - Reporte como_vamos.xlsx successfully load
[2025-02-13T18:25:59.200-0500] {subprocess.py:106} INFO - 2025-02-13 18:25:59,200 - etl_ex_bbva - INFO - etl_ex_bbva.py success execution
[2025-02-13T18:25:59.201-0500] {subprocess.py:106} INFO - Conexi√≥n exitosa a la base de datos: calidad_etl
[2025-02-13T18:25:59.404-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-13T18:25:59.439-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-13T18:25:59.440-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=etl_ex_bbva, run_id=manual__2025-02-13T23:24:05.217618+00:00, execution_date=20250213T232405, start_date=20250213T232550, end_date=20250213T232559
[2025-02-13T18:25:59.485-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T18:25:59.506-0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T18:25:59.509-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
