[2025-02-01T03:49:31.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T03:49:31.758+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.bot_ex_bbva manual__2025-02-01T03:49:26.828354+00:00 [queued]>
[2025-02-01T03:49:31.815+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.bot_ex_bbva manual__2025-02-01T03:49:26.828354+00:00 [queued]>
[2025-02-01T03:49:31.824+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T03:49:31.927+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): bot_ex_bbva> on 2025-02-01 03:49:26.828354+00:00
[2025-02-01T03:49:31.953+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T03:49:31.959+0000] {standard_task_runner.py:72} INFO - Started process 2126 to run task
[2025-02-01T03:49:31.968+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'bot_ex_bbva', 'manual__2025-02-01T03:49:26.828354+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmp9cg176h9']
[2025-02-01T03:49:31.984+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask bot_ex_bbva
[2025-02-01T03:49:32.225+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.bot_ex_bbva manual__2025-02-01T03:49:26.828354+00:00 [running]> on host 56024cb05cfe
[2025-02-01T03:49:32.604+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='bot_ex_bbva' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T03:49:26.828354+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T03:49:26.828354+00:00'
[2025-02-01T03:49:32.609+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T03:49:32.695+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-01T03:49:32.699+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_etl_ex_bbva.py']
[2025-02-01T03:49:32.730+0000] {subprocess.py:99} INFO - Output:
[2025-02-01T03:49:37.348+0000] {subprocess.py:106} INFO - 2025-02-01 03:49:37,348 - bot_etl_ex_bbva - INFO - Bot ETL Exito-BBVA started
[2025-02-01T03:49:38.969+0000] {subprocess.py:106} INFO - 2025-02-01 03:49:38,969 - bot_etl_ex_bbva - INFO - Conexi√≥n al Selenium Hub establecida correctamente
[2025-02-01T03:49:40.362+0000] {subprocess.py:106} INFO - 2025-02-01 03:49:40,362 - bot_etl_ex_bbva - INFO - Credentials input success
[2025-02-01T03:49:41.199+0000] {subprocess.py:106} INFO - 2025-02-01 03:49:41,199 - bot_etl_ex_bbva - INFO - Click in login button
[2025-02-01T03:49:51.254+0000] {subprocess.py:106} INFO - 2025-02-01 03:49:51,254 - bot_etl_ex_bbva - INFO - Loging success
[2025-02-01T03:49:53.648+0000] {subprocess.py:106} INFO - 2025-02-01 03:49:53,648 - bot_etl_ex_bbva - INFO - Input file succes
[2025-02-01T03:50:05.541+0000] {subprocess.py:106} INFO - 2025-02-01 03:50:05,540 - bot_etl_ex_bbva - INFO - Click in Cargar
[2025-02-01T03:50:26.491+0000] {subprocess.py:106} INFO - 2025-02-01 03:50:26,491 - bot_etl_ex_bbva - INFO - bot_etl_ex_bbva finish execution
[2025-02-01T03:50:26.669+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-01T03:50:26.724+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T03:50:26.726+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=bot_ex_bbva, run_id=manual__2025-02-01T03:49:26.828354+00:00, execution_date=20250201T034926, start_date=20250201T034931, end_date=20250201T035026
[2025-02-01T03:50:26.804+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T03:50:26.836+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T03:50:26.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
