[2025-02-07T09:50:56.235-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T09:50:56.258-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos manual__2025-02-07T14:50:55.036502+00:00 [queued]>
[2025-02-07T09:50:56.269-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos manual__2025-02-07T14:50:55.036502+00:00 [queued]>
[2025-02-07T09:50:56.271-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-02-07T09:50:56.288-0500] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): task_bot_como_vamos> on 2025-02-07 14:50:55.036502+00:00
[2025-02-07T09:50:56.294-0500] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=38285) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T09:50:56.296-0500] {standard_task_runner.py:72} INFO - Started process 38286 to run task
[2025-02-07T09:50:56.297-0500] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_reporte_como_vamos', 'task_bot_como_vamos', 'manual__2025-02-07T14:50:55.036502+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/etl_como_vamos_dag.py', '--cfg-path', '/tmp/tmpvdndhu8e']
[2025-02-07T09:50:56.299-0500] {standard_task_runner.py:105} INFO - Job 72: Subtask task_bot_como_vamos
[2025-02-07T09:50:56.370-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_reporte_como_vamos.task_bot_como_vamos manual__2025-02-07T14:50:55.036502+00:00 [running]> on host 21f1c1b48730
[2025-02-07T09:50:56.495-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_reporte_como_vamos' AIRFLOW_CTX_TASK_ID='task_bot_como_vamos' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T14:50:55.036502+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-07T14:50:55.036502+00:00'
[2025-02-07T09:50:56.496-0500] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T09:50:56.525-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-07T09:50:56.526-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/bot_reporte_como_vamos.py']
[2025-02-07T09:50:56.544-0500] {subprocess.py:99} INFO - Output:
[2025-02-07T09:50:59.878-0500] {subprocess.py:106} INFO - ic| report_date: '06/02/2025'
[2025-02-07T09:50:59.878-0500] {subprocess.py:106} INFO - 2025-02-07 09:50:59,878 - bot_como_vamos - INFO - Starting script bot_como_vamos.py
[2025-02-07T09:51:00.647-0500] {subprocess.py:106} INFO - 2025-02-07 09:51:00,647 - bot_como_vamos - INFO - Conexi√≥n al Selenium Hub establecida correctamente
[2025-02-07T09:51:58.945-0500] {subprocess.py:106} INFO - ic| login_success: <selenium.webdriver.remote.webelement.WebElement (session="c11a815b2777896af29801956127e875", element="f.46E747B1B6081A84C5DD6CE0A0BC380D.d.D00565C8F6FBE88FE291E20CD8054900.e.77")>
[2025-02-07T09:51:58.951-0500] {subprocess.py:106} INFO - 2025-02-07 09:51:58,943 - bot_como_vamos - INFO - Loging success
[2025-02-07T09:52:09.188-0500] {subprocess.py:106} INFO - 2025-02-07 09:52:09,184 - bot_como_vamos - INFO - Click in menu button successfully
[2025-02-07T09:52:19.406-0500] {subprocess.py:106} INFO - 2025-02-07 09:52:19,405 - bot_como_vamos - INFO - Input dates successfully
[2025-02-07T09:52:29.532-0500] {subprocess.py:106} INFO - 2025-02-07 09:52:29,532 - bot_como_vamos - INFO - Click in 'Empresas Y Negocios' successfully
[2025-02-07T09:53:03.750-0500] {subprocess.py:106} INFO - 2025-02-07 09:53:03,749 - assets - INFO - Waiting for download file...............
[2025-02-07T09:53:03.832-0500] {subprocess.py:106} INFO - ic| file: '.com.google.Chrome.hdd2hi'
[2025-02-07T09:53:08.839-0500] {subprocess.py:106} INFO - ic| file: 'Unconfirmed 416550.crdownload'
[2025-02-07T09:53:13.844-0500] {subprocess.py:106} INFO - ic| file: 'Reporte como_vamos.xlsx'
[2025-02-07T09:53:13.846-0500] {subprocess.py:106} INFO - 2025-02-07 09:53:13,844 - bot_como_vamos - INFO - Download Reporte como_vamos succesfully
[2025-02-07T09:53:14.517-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-07T09:53:14.632-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T09:53:14.635-0500] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reporte_como_vamos, task_id=task_bot_como_vamos, run_id=manual__2025-02-07T14:50:55.036502+00:00, execution_date=20250207T145055, start_date=20250207T145056, end_date=20250207T145314
[2025-02-07T09:53:14.702-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T09:53:14.793-0500] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-07T09:53:14.797-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
